real_hh_ind = [
    'H150104_TENURE_STA',
    'H150113_RADIO_QTY',
    'H150114_TV_QTY',
    'H150115_VCD_QTY',
    'H150116_STEREO_QTY',
    'H150117_REF_QTY',
    'H150118_WASH_QTY',
    'H150119_AIRCON_QTY',
    'H150121_LANDLINE_QTY',
    'H150122_CELL_QTY',
    'H150123_COMP_QTY',
    'H150124_OVEN_QTY',
    'H150120_CAR_QTY',
    'H150125_BANCA_QTY',
    'H150126_MOTOR_QTY',
    'H150102_ROOF',
    'H150103_WALLS',
    'H150101_BLDG_TYPE',
    'H150111_WATER_SUPPLY',
    'H150109_TOILET',
    'H150110_ELECTRICITY',
    'domestic_helper',
    'RPROV',
]
real_id_ind = [
    'FSIZE',
    'hh_sex',
    'hh_ms',
    'occ4d_1',
    'occ4d_2',
    'occ4d_3',
    'occ4d_4',
    'occ4d_5',
    'occ4d_6',
    'occ4d_7',
    'occ4d_8',
    'occ4d_9',
    'age_0_5',
    'age_13_17',
    'age_18_64',
    'age_65p',
    'age_6_12',
    'educ_college',
    'educ_none',
    'educ_other',
    'educ_postgrad',
    'educ_primary',
    'educ_secondary'
]
real_com_ind = [
    'poblacion',
    'street_pattern',
    'acc_nat_hwy',
    'cemetery',
    'city_hall',
    'market',
    'elem_sch',
    'hs_sch',
    'health',
    'hospital',
    'plaza',
    'port',
    'library',
    'waterworks_system',
    'cell_signal',
    'landline',
    'post_office',
    'fire_station',
]

hh_ind = [
    'C(H150104_TENURE_STA)',
    'H150113_RADIO_QTY',
    'H150114_TV_QTY',
    'H150115_VCD_QTY',
    'H150116_STEREO_QTY',
    'H150117_REF_QTY',
    'H150118_WASH_QTY',
    'H150119_AIRCON_QTY',
    'H150121_LANDLINE_QTY',
    'H150122_CELL_QTY',
    'H150123_COMP_QTY',
    'H150124_OVEN_QTY',
    'H150120_CAR_QTY',
    'H150125_BANCA_QTY',
    'H150126_MOTOR_QTY',
    'C(H150102_ROOF)',
    'C(H150103_WALLS)',
    'C(H150101_BLDG_TYPE)',
    'C(H150111_WATER_SUPPLY)',
    'C(H150109_TOILET)',
    'C(H150110_ELECTRICITY)',
    'domestic_helper',
    'C(RPROV)',
]

id_ind = [
    'FSIZE',
    'C(hh_sex)',
    'C(hh_ms)',
    'occ4d_1',
    'occ4d_2',
    'occ4d_3',
    'occ4d_4',
    'occ4d_5',
    'occ4d_6',
    'occ4d_7',
    'occ4d_8',
    'occ4d_9',
    'age_0_5',
    'age_13_17',
    'age_18_64',
    'age_65p',
    'age_6_12',
    'educ_college',
    'educ_none',
    'educ_other',
    'educ_postgrad',
    'educ_primary',
    'educ_secondary'
    ]

com_ind = [
    'poblacion',
    'street_pattern',
    'acc_nat_hwy',
    'cemetery',
    'city_hall',
    'market',
    'elem_sch',
    'hs_sch',
    'health',
    'hospital',
    'plaza',
    'port',
    'library',
    'waterworks_system',
    'cell_signal',
    'landline',
    'post_office',
    'fire_station',
]

label_map = {
    # ── Household-asset quantities ──────────────────────────────────────
    "H150113_RADIO_QTY":     "Radios (qty)",
    "H150114_TV_QTY":        "Televisions (qty)",
    "H150115_VCD_QTY":       "DVD / VCD players (qty)",
    "H150116_STEREO_QTY":    "Stereos (qty)",
    "H150117_REF_QTY":       "Refrigerators (qty)",
    "H150118_WASH_QTY":      "Washing machines (qty)",
    "H150119_AIRCON_QTY":    "Air-conditioners (qty)",
    "H150121_LANDLINE_QTY":  "Land-line phones (qty)",
    "H150122_CELL_QTY":      "Mobile phones (qty)",
    "H150123_COMP_QTY":      "Computers (qty)",
    "H150124_OVEN_QTY":      "Ovens / microwaves (qty)",
    "H150126_MOTOR_QTY":     "Motorcycles / tricycles (qty)",
    "H150120_CAR_QTY":       "Cars (qty)",
    "H150125_BANCA_QTY":      "Banca (qty)",
    "RPROV":               "Province of residence",

    # ── Household composition & services ────────────────────────────────
    "FSIZE":             "Household size",
    "domestic_helper":   "Domestic helper present (qty)",

    # ── Community / infrastructure distances or counts ─────────────────
    "poblacion":           "Branagay located in poblacion / city district",
    "street_pattern":      "Presence of street patterns in Barangay",
    "acc_nat_hwy":         "Access to national highway in Barangay",
    "cemetery":            "Presence of cemetery in Barangay",
    "city_hall":           "Presence of city hall / prov. capitol in Barangay",
    "market":              "Presence of market in Barangay",
    "elem_sch":            "Presence of elementary school in Barangay",
    "hs_sch":              "Presence of high school in Barangay",
    "health":              "Presence of health centre in Barangay",
    "hospital":            "Presence of hospital in Barangay",
    "plaza":               "Presence of plaza in Barangay",
    "port":                "Presence of port in Barangay",
    "library":             "Presence of library in Barangay",
    "waterworks_system":   "Presence of community waterworks system in Barangay",
    "cell_signal":         "Available cell-signal in Barangay (yes/no)",
    "landline":            "Presence of landline telephone system or calling station in Barangay",
    "post_office":         "Presence of post office in Barangay",
    "fire_station":        "Presence of fire station in Barangay",

    # ── PSOC major-group occupation shares ──────────────────────────────
    "occ4d_1": "Officials & Managers",
    "occ4d_2": "Professionals",
    "occ4d_3": "Technicians & Associate Prof.",
    "occ4d_4": "Clerks",
    "occ4d_5": "Service & Sales Workers",
    "occ4d_6": "Skilled Agri- & Fishery Workers",
    "occ4d_7": "Trades & Related Workers",
    "occ4d_8": "Plant & Machine Operators / Assemblers",
    "occ4d_9": "Elementary Occupations",

    # ── Age-structure shares  ────────────────────────
    "age_0_5":    "Ages 0–5",
    "age_6_12":   "Ages 6–12",
    "age_13_17":  "Ages 13–17",
    "age_18_64":  "Ages 18–64",
    "age_65p":    "Ages 65+",

    # ── Education-level shares  ──────────────────────
    "educ_none":      "Education – none",
    "educ_primary":   "Education – primary",
    "educ_secondary": "Education – secondary",
    "educ_college":   "Education – college",
    "educ_postgrad":  "Education – post-graduate",
    "educ_other":     "Education – other",

    # ── Categorical household variables ────────────────────────────────
    "H150104_TENURE_STA":    "Tenure status",
    "H150102_ROOF":          "Roof material",
    "H150103_WALLS":         "Wall material",
    "H150101_BLDG_TYPE":     "Building type",
    "H150111_WATER_SUPPLY":  "Water supply",
    "H150109_TOILET":        "Toilet type",
    "H150110_ELECTRICITY":   "Electricity access",
    "hh_sex":                "Head of household sex",
    "hh_ms":                 "Head of household marital status",
}

label_map2 = {
    # ── Household-asset quantities ──────────────────────────────────────
    "H150113_RADIO_QTY":     "Radios (qty)",
    "H150114_TV_QTY":        "Televisions (qty)",
    "H150115_VCD_QTY":       "DVD / VCD players (qty)",
    "H150116_STEREO_QTY":    "Stereos (qty)",
    "H150117_REF_QTY":       "Refrigerators (qty)",
    "H150118_WASH_QTY":      "Washing machines (qty)",
    "H150119_AIRCON_QTY":    "Air-conditioners (qty)",
    "H150121_LANDLINE_QTY":  "Land-line phones (qty)",
    "H150122_CELL_QTY":      "Mobile phones (qty)",
    "H150123_COMP_QTY":      "Computers (qty)",
    "H150124_OVEN_QTY":      "Ovens / microwaves (qty)",
    "H150126_MOTOR_QTY":     "Motorcycles / tricycles (qty)",
    "H150120_CAR_QTY":       "Cars (qty)",
    "H150125_BANCA_QTY":      "Banca (qty)",
    "RPROV":               "Province of residence",

    # ── Household composition & services ────────────────────────────────
    "FSIZE":             "Household size",
    "domestic_helper":   "Domestic helper present (qty)",

    # ── Community / infrastructure distances or counts ─────────────────
    "poblacion":           "Branagay located in poblacion / city district",
    "street_pattern":      "Presence of street patterns in Barangay",
    "acc_nat_hwy":         "Access to national highway in Barangay",
    "cemetery":            "Presence of cemetery in Barangay",
    "city_hall":           "Presence of city hall / prov. capitol in Barangay",
    "market":              "Presence of market in Barangay",
    "elem_sch":            "Presence of elementary school in Barangay",
    "hs_sch":              "Presence of high school in Barangay",
    "health":              "Presence of health centre in Barangay",
    "hospital":            "Presence of hospital in Barangay",
    "plaza":               "Presence of plaza in Barangay",
    "port":                "Presence of port in Barangay",
    "library":             "Presence of library in Barangay",
    "waterworks_system":   "Presence of community waterworks system in Barangay",
    "cell_signal":         "Available cell-signal in Barangay (yes/no)",
    "landline":            "Presence of landline telephone system or calling station in Barangay",
    "post_office":         "Presence of post office in Barangay",
    "fire_station":        "Presence of fire station in Barangay",

    # ── PSOC major-group occupation shares ──────────────────────────────
    "occ4d_1": "Officials & Managers",
    "occ4d_2": "Professionals",
    "occ4d_3": "Technicians & Associate Prof.",
    "occ4d_4": "Clerks",
    "occ4d_5": "Service & Sales Workers",
    "occ4d_6": "Skilled Agri- & Fishery Workers",
    "occ4d_7": "Trades & Related Workers",
    "occ4d_8": "Plant & Machine Operators / Assemblers",
    "occ4d_9": "Elementary Occupations",

    # ── Age-structure shares  ────────────────────────
    "age_0_5":    "Ages 0–5",
    "age_6_12":   "Ages 6–12",
    "age_13_17":  "Ages 13–17",
    "age_18_64":  "Ages 18–64",
    "age_65p":    "Ages 65+",

    # ── Education-level shares  ──────────────────────
    "educ_none":      "Education – none",
    "educ_primary":   "Education – primary",
    "educ_secondary": "Education – secondary",
    "educ_college":   "Education – college",
    "educ_postgrad":  "Education – post-graduate",
    "educ_other":     "Education – other",

    # ── Categorical household variables ────────────────────────────────
    "H150104_TENURE_STA":    "Tenure status",
    "H150102_ROOF":          "Roof material",
    "H150103_WALLS":         "Wall material",
    "H150101_BLDG_TYPE":     "Building type",
    "H150111_WATER_SUPPLY":  "Water supply",
    "H150109_TOILET":        "Toilet type",
    "H150110_ELECTRICITY":   "Electricity access",
    "hh_sex":                "Head of household sex",
    "hh_ms":                 "Head of household marital status",
}
